/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* hdlname = "\\lift_schedule" *)
(* src = "lift_schedule.v:4.1-194.10" *)
module \$paramod$73e12f780b28ea4983629c398f0c11da23bd7b50\lift_schedule (clk, rst, floor_request, door_obstruction, emergency_stop, current_floor, door_open, motor_up, motor_down, state_dbg);
  (* src = "lift_schedule.v:104.5-170.8" *)
  wire [3:0] _000_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [6:0] _001_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _002_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:84.12-84.14" *)
  wire _003_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:84.16-84.18" *)
  wire _004_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/bin/../share/yosys/xilinx/lut_map.v:78.12-78.14" *)
  wire _005_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _006_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/bin/../share/yosys/xilinx/lut_map.v:78.12-78.14" *)
  wire _007_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _008_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:84.12-84.14" *)
  wire _009_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:84.16-84.18" *)
  wire _010_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/bin/../share/yosys/xilinx/lut_map.v:78.12-78.14" *)
  wire _011_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _012_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/bin/../share/yosys/xilinx/lut_map.v:78.12-78.14" *)
  wire _013_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _014_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [6:0] _015_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:78.12-78.14" *)
  wire _016_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _017_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [6:0] _018_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:78.12-78.14" *)
  wire _019_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _020_;
  wire _021_;
  wire _022_;
  (* force_downto = 32'd1 *)
  (* src = "lift_schedule.v:0.0-0.0|/usr/bin/../share/yosys/xilinx/arith_map.v:128.21-128.23" *)
  wire [31:0] _023_;
  (* force_downto = 32'd1 *)
  (* src = "lift_schedule.v:0.0-0.0|/usr/bin/../share/yosys/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 12 13 14 16 17 18 20 21 22 24 25 26 28 29 30 31" *)
  wire [31:0] _024_;
  (* force_downto = 32'd1 *)
  (* src = "lift_schedule.v:0.0-0.0|/usr/bin/../share/yosys/xilinx/arith_map.v:112.26-112.27" *)
  wire [31:0] _025_;
  (* force_downto = 32'd1 *)
  (* src = "lift_schedule.v:0.0-0.0|lift_schedule.v:118.13-168.20|/usr/bin/../share/yosys/techmap.v:137.23-137.24" *)
  wire [1:0] _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  (* force_downto = 32'd1 *)
  (* src = "lift_schedule.v:0.0-0.0|lift_schedule.v:118.13-168.20|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  (* unused_bits = "1" *)
  wire [1:0] _030_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [5:0] _031_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [3:0] _032_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [5:0] _033_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [4:0] _034_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [4:0] _035_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _036_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [5:0] _037_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [4:0] _038_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _039_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [5:0] _040_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _041_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [5:0] _042_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [5:0] _043_;
  (* src = "lift_schedule.v:5.30-5.33" *)
  input clk;
  wire clk;
  (* src = "lift_schedule.v:10.30-10.43" *)
  output [1:0] current_floor;
  wire [1:0] current_floor;
  (* src = "lift_schedule.v:8.30-8.46" *)
  input door_obstruction;
  wire door_obstruction;
  (* src = "lift_schedule.v:11.30-11.39" *)
  output door_open;
  wire door_open;
  (* src = "lift_schedule.v:27.22-27.32" *)
  wire [1:0] door_timer;
  (* src = "lift_schedule.v:9.30-9.44" *)
  input emergency_stop;
  wire emergency_stop;
  (* src = "lift_schedule.v:7.30-7.43" *)
  input [3:0] floor_request;
  wire [3:0] floor_request;
  (* src = "lift_schedule.v:36.13-36.14" *)
  wire [31:0] i;
  (* src = "lift_schedule.v:13.30-13.40" *)
  output motor_down;
  wire motor_down;
  (* src = "lift_schedule.v:12.30-12.38" *)
  output motor_up;
  wire motor_up;
  (* src = "lift_schedule.v:26.22-26.32" *)
  wire [1:0] move_timer;
  (* src = "lift_schedule.v:32.38-32.51" *)
  (* unused_bits = "1" *)
  wire [1:0] next_floor_dn;
  (* src = "lift_schedule.v:32.23-32.36" *)
  (* unused_bits = "1" *)
  wire [1:0] next_floor_up;
  (* src = "lift_schedule.v:25.22-25.31" *)
  wire [3:0] pending_q;
  (* src = "lift_schedule.v:6.30-6.33" *)
  input rst;
  wire rst;
  (* src = "lift_schedule.v:28.22-28.31" *)
  wire saved_dir;
  (* src = "lift_schedule.v:23.24-23.31" *)
  wire [2:0] state_d;
  (* src = "lift_schedule.v:14.30-14.39" *)
  output [2:0] state_dbg;
  wire [2:0] state_dbg;
  (* src = "lift_schedule.v:23.15-23.22" *)
  wire [2:0] state_q;
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _044_ (
    .I0(state_q[0]),
    .I1(_001_[6]),
    .O(motor_up)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _045_ (
    .I0(state_q[2]),
    .I1(state_q[1]),
    .O(_001_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'hb)
  ) _046_ (
    .I0(state_q[2]),
    .I1(door_open),
    .O(_036_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _047_ (
    .I0(state_q[1]),
    .I1(state_q[0]),
    .O(door_open)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h18)
  ) _048_ (
    .I0(state_q[1]),
    .I1(state_q[0]),
    .I2(state_q[2]),
    .O(motor_down)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h1)
  ) _049_ (
    .I0(door_obstruction),
    .I1(emergency_stop),
    .O(_034_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h000000ef00000000)
  ) _050_ (
    .I0(door_timer[1]),
    .I1(door_obstruction),
    .I2(door_timer[0]),
    .I3(state_q[1]),
    .I4(state_q[2]),
    .I5(state_q[0]),
    .O(_039_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'habaaa8aaafaaacaa)
  ) _051_ (
    .I0(emergency_stop),
    .I1(_042_[1]),
    .I2(_042_[2]),
    .I3(_042_[3]),
    .I4(_042_[4]),
    .I5(_035_[1]),
    .O(_021_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'ha00c0ca000000000)
  ) _052_ (
    .I0(_033_[5]),
    .I1(_040_[1]),
    .I2(current_floor[0]),
    .I3(state_q[0]),
    .I4(current_floor[1]),
    .I5(_001_[6]),
    .O(_042_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h1)
  ) _053_ (
    .I0(pending_q[2]),
    .I1(floor_request[2]),
    .O(_033_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h1)
  ) _054_ (
    .I0(pending_q[3]),
    .I1(floor_request[3]),
    .O(_040_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'haa0a0aaa22aaaa22)
  ) _055_ (
    .I0(_001_[0]),
    .I1(_001_[1]),
    .I2(_001_[2]),
    .I3(state_q[0]),
    .I4(current_floor[1]),
    .I5(current_floor[0]),
    .O(_002_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _056_ (
    .I0(1'h1),
    .I1(_002_),
    .O(_042_[3]),
    .S(_001_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h1)
  ) _057_ (
    .I0(pending_q[1]),
    .I1(floor_request[1]),
    .O(_001_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h1)
  ) _058_ (
    .I0(pending_q[0]),
    .I1(floor_request[0]),
    .O(_001_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _059_ (
    .I0(move_timer[1]),
    .I1(move_timer[0]),
    .O(_001_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd987409)
  ) _060_ (
    .I0(floor_request[2]),
    .I1(pending_q[2]),
    .I2(pending_q[3]),
    .I3(floor_request[3]),
    .I4(current_floor[0]),
    .O(_018_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h0100)
  ) _061_ (
    .I0(_034_[0]),
    .I1(state_q[2]),
    .I2(state_q[0]),
    .I3(_034_[1]),
    .O(_042_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/bin/../share/yosys/xilinx/lut_map.v:79.45-79.70|/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h0f0f0f0f0f0f1fff)
  ) _062_ (
    .I0(pending_q[2]),
    .I1(floor_request[2]),
    .I2(current_floor[1]),
    .I3(current_floor[0]),
    .I4(pending_q[1]),
    .I5(floor_request[1]),
    .O(_005_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT2 #(
    .INIT(4'h1)
  ) _063_ (
    .I0(current_floor[1]),
    .I1(current_floor[0]),
    .O(_006_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _064_ (
    .I0(_005_),
    .I1(_006_),
    .O(_003_),
    .S(floor_request[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/bin/../share/yosys/xilinx/lut_map.v:79.45-79.70|/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT2 #(
    .INIT(4'h1)
  ) _065_ (
    .I0(current_floor[1]),
    .I1(current_floor[0]),
    .O(_007_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT2 #(
    .INIT(4'h1)
  ) _066_ (
    .I0(current_floor[1]),
    .I1(current_floor[0]),
    .O(_008_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _067_ (
    .I0(_007_),
    .I1(_008_),
    .O(_004_),
    .S(floor_request[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:87.13-87.52" *)
  MUXF8 _068_ (
    .I0(_003_),
    .I1(_004_),
    .O(_034_[1]),
    .S(pending_q[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/bin/../share/yosys/xilinx/lut_map.v:79.45-79.70|/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h0f0f0f0f0f0f000e)
  ) _069_ (
    .I0(pending_q[1]),
    .I1(floor_request[1]),
    .I2(current_floor[1]),
    .I3(current_floor[0]),
    .I4(pending_q[2]),
    .I5(floor_request[2]),
    .O(_011_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT2 #(
    .INIT(4'h7)
  ) _070_ (
    .I0(current_floor[1]),
    .I1(current_floor[0]),
    .O(_012_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _071_ (
    .I0(_011_),
    .I1(_012_),
    .O(_009_),
    .S(pending_q[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/bin/../share/yosys/xilinx/lut_map.v:79.45-79.70|/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT2 #(
    .INIT(4'h7)
  ) _072_ (
    .I0(current_floor[1]),
    .I1(current_floor[0]),
    .O(_013_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT2 #(
    .INIT(4'h7)
  ) _073_ (
    .I0(current_floor[1]),
    .I1(current_floor[0]),
    .O(_014_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _074_ (
    .I0(_013_),
    .I1(_014_),
    .O(_010_),
    .S(pending_q[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:87.13-87.52" *)
  MUXF8 _075_ (
    .I0(_009_),
    .I1(_010_),
    .O(_034_[0]),
    .S(floor_request[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h70)
  ) _076_ (
    .I0(_039_[2]),
    .I1(_034_[3]),
    .I2(_041_[2]),
    .O(_042_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hff33ff0affffffff)
  ) _077_ (
    .I0(move_timer[0]),
    .I1(emergency_stop),
    .I2(move_timer[1]),
    .I3(state_q[1]),
    .I4(state_q[0]),
    .I5(state_q[2]),
    .O(_041_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd87031808)
  ) _078_ (
    .I0(state_q[0]),
    .I1(emergency_stop),
    .I2(state_q[1]),
    .I3(state_q[2]),
    .I4(_001_[0]),
    .O(_022_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd61439)
  ) _079_ (
    .I0(_033_[0]),
    .I1(_036_[0]),
    .I2(_033_[2]),
    .I3(_038_[3]),
    .I4(_001_[2]),
    .O(_000_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h0777)
  ) _080_ (
    .I0(_032_[0]),
    .I1(_032_[1]),
    .I2(_032_[2]),
    .I3(_032_[3]),
    .O(_033_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h0000000000000001)
  ) _081_ (
    .I0(_015_[0]),
    .I1(_025_[15]),
    .I2(_025_[16]),
    .I3(_025_[17]),
    .I4(_025_[18]),
    .I5(_025_[31]),
    .O(_032_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h0000000000000001)
  ) _082_ (
    .I0(_025_[19]),
    .I1(_025_[20]),
    .I2(_025_[21]),
    .I3(_025_[22]),
    .I4(_025_[23]),
    .I5(_025_[24]),
    .O(_032_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h8000000000000000)
  ) _083_ (
    .I0(_015_[0]),
    .I1(_025_[15]),
    .I2(_025_[16]),
    .I3(_025_[17]),
    .I4(_025_[18]),
    .I5(_025_[31]),
    .O(_032_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h8000000000000000)
  ) _084_ (
    .I0(_025_[19]),
    .I1(_025_[20]),
    .I2(_025_[21]),
    .I3(_025_[22]),
    .I4(_025_[23]),
    .I5(_025_[24]),
    .O(_032_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h000088880000f000)
  ) _085_ (
    .I0(_031_[0]),
    .I1(_031_[1]),
    .I2(_031_[2]),
    .I3(_031_[3]),
    .I4(_031_[4]),
    .I5(_025_[7]),
    .O(_033_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd1)
  ) _086_ (
    .I0(_015_[0]),
    .I1(_025_[10]),
    .I2(_025_[11]),
    .I3(_025_[12]),
    .I4(_025_[8]),
    .O(_031_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h0000000000000001)
  ) _087_ (
    .I0(_025_[13]),
    .I1(_025_[14]),
    .I2(_025_[9]),
    .I3(_025_[6]),
    .I4(_025_[5]),
    .I5(_025_[4]),
    .O(_031_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h8000000000000000)
  ) _088_ (
    .I0(_025_[13]),
    .I1(_025_[14]),
    .I2(_025_[9]),
    .I3(_025_[6]),
    .I4(_025_[5]),
    .I5(_025_[4]),
    .O(_031_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd2147483648)
  ) _089_ (
    .I0(_015_[0]),
    .I1(_025_[10]),
    .I2(_025_[11]),
    .I3(_025_[12]),
    .I4(_025_[8]),
    .O(_031_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:79.45-79.70|/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hfffffffffffffffe)
  ) _090_ (
    .I0(_015_[0]),
    .I1(_015_[1]),
    .I2(_015_[2]),
    .I3(_015_[3]),
    .I4(_015_[4]),
    .I5(_015_[5]),
    .O(_016_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h7fffffffffffffff)
  ) _091_ (
    .I0(_015_[0]),
    .I1(_015_[1]),
    .I2(_015_[2]),
    .I3(_015_[3]),
    .I4(_015_[4]),
    .I5(_015_[5]),
    .O(_017_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _092_ (
    .I0(_016_),
    .I1(_017_),
    .O(_031_[4]),
    .S(_015_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd1)
  ) _093_ (
    .I0(emergency_stop),
    .I1(_025_[2]),
    .I2(_025_[1]),
    .I3(_025_[0]),
    .I4(_015_[0]),
    .O(_038_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h00000000bfffffff)
  ) _094_ (
    .I0(_033_[0]),
    .I1(_033_[3]),
    .I2(_033_[2]),
    .I3(_025_[0]),
    .I4(_015_[0]),
    .I5(_001_[1]),
    .O(_000_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd268435456)
  ) _095_ (
    .I0(state_q[2]),
    .I1(emergency_stop),
    .I2(door_open),
    .I3(_025_[2]),
    .I4(_025_[1]),
    .O(_033_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h00000000efffffff)
  ) _096_ (
    .I0(_033_[0]),
    .I1(_025_[0]),
    .I2(_033_[2]),
    .I3(_033_[3]),
    .I4(_015_[0]),
    .I5(_033_[5]),
    .O(_000_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h00000000bfffffff)
  ) _097_ (
    .I0(_033_[0]),
    .I1(_043_[1]),
    .I2(_033_[2]),
    .I3(_025_[0]),
    .I4(_015_[0]),
    .I5(_040_[1]),
    .O(_000_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd16777216)
  ) _098_ (
    .I0(state_q[2]),
    .I1(emergency_stop),
    .I2(_025_[1]),
    .I3(_025_[2]),
    .I4(door_open),
    .O(_043_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'he11e)
  ) _099_ (
    .I0(state_q[2]),
    .I1(state_q[0]),
    .I2(current_floor[0]),
    .I3(current_floor[1]),
    .O(_026_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h1)
  ) _100_ (
    .I0(_035_[2]),
    .I1(move_timer[0]),
    .O(_030_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'hfacf)
  ) _101_ (
    .I0(state_q[0]),
    .I1(emergency_stop),
    .I2(state_q[1]),
    .I3(state_q[2]),
    .O(_035_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd259985167)
  ) _102_ (
    .I0(_034_[0]),
    .I1(_035_[1]),
    .I2(_035_[2]),
    .I3(_035_[3]),
    .I4(_035_[4]),
    .O(state_d[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4009754624)
  ) _103_ (
    .I0(_034_[0]),
    .I1(_034_[1]),
    .I2(_034_[2]),
    .I3(_034_[3]),
    .I4(state_q[0]),
    .O(_035_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h10)
  ) _104_ (
    .I0(door_obstruction),
    .I1(door_timer[1]),
    .I2(door_timer[0]),
    .O(_034_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:79.45-79.70|/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT5 #(
    .INIT(32'd202)
  ) _105_ (
    .I0(_001_[2]),
    .I1(_001_[1]),
    .I2(current_floor[0]),
    .I3(emergency_stop),
    .I4(state_q[0]),
    .O(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT3 #(
    .INIT(8'h02)
  ) _106_ (
    .I0(_018_[2]),
    .I1(emergency_stop),
    .I2(state_q[0]),
    .O(_020_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _107_ (
    .I0(_019_),
    .I1(_020_),
    .O(_035_[1]),
    .S(current_floor[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h1)
  ) _108_ (
    .I0(state_q[1]),
    .I1(state_q[2]),
    .O(_035_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hfbf0f0f000000000)
  ) _109_ (
    .I0(_034_[0]),
    .I1(_034_[1]),
    .I2(_035_[1]),
    .I3(_034_[2]),
    .I4(_037_[4]),
    .I5(_035_[4]),
    .O(state_d[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _110_ (
    .I0(emergency_stop),
    .I1(state_q[0]),
    .O(_037_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h11f0)
  ) _111_ (
    .I0(state_q[1]),
    .I1(state_q[0]),
    .I2(emergency_stop),
    .I3(state_q[2]),
    .O(state_d[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _112_ (
    .I(current_floor[0]),
    .O(next_floor_dn[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _113_ (
    .I(current_floor[1]),
    .O(_023_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_schedule.v:0.0-0.0|/usr/bin/../share/yosys/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _114_ (
    .CI(1'h0),
    .CO(_024_[3:0]),
    .CYINIT(1'h1),
    .DI(4'h0),
    .O({ _015_[0], _025_[2:0] }),
    .S({ 2'h3, _023_[1], next_floor_dn[0] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_schedule.v:0.0-0.0|/usr/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _115_ (
    .CI(_024_[3]),
    .CO(_024_[7:4]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_025_[7:4]),
    .S(4'hf)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_schedule.v:0.0-0.0|/usr/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _116_ (
    .CI(_024_[7]),
    .CO(_024_[11:8]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_025_[11:8]),
    .S(4'hf)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_schedule.v:0.0-0.0|/usr/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _117_ (
    .CI(_024_[11]),
    .CO(_024_[15:12]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_025_[15:12]),
    .S(4'hf)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_schedule.v:0.0-0.0|/usr/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _118_ (
    .CI(_024_[15]),
    .CO(_024_[19:16]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_025_[19:16]),
    .S(4'hf)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_schedule.v:0.0-0.0|/usr/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _119_ (
    .CI(_024_[19]),
    .CO(_024_[23:20]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_025_[23:20]),
    .S(4'hf)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_schedule.v:0.0-0.0|/usr/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _120_ (
    .CI(_024_[23]),
    .CO(_024_[27:24]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O({ _015_[3:1], _025_[24] }),
    .S(4'hf)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_schedule.v:0.0-0.0|/usr/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _121_ (
    .CI(_024_[27]),
    .CO(_024_[31:28]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O({ _025_[31], _015_[6:4] }),
    .S(4'hf)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_schedule.v:104.5-170.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _122_ (
    .C(clk),
    .CE(1'h1),
    .D(_000_[0]),
    .Q(pending_q[0]),
    .R(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_schedule.v:104.5-170.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _123_ (
    .C(clk),
    .CE(1'h1),
    .D(_000_[1]),
    .Q(pending_q[1]),
    .R(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_schedule.v:104.5-170.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _124_ (
    .C(clk),
    .CE(1'h1),
    .D(_000_[2]),
    .Q(pending_q[2]),
    .R(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_schedule.v:104.5-170.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _125_ (
    .C(clk),
    .CE(1'h1),
    .D(_000_[3]),
    .Q(pending_q[3]),
    .R(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_schedule.v:104.5-170.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _126_ (
    .C(clk),
    .CE(_022_),
    .D(next_floor_dn[0]),
    .Q(current_floor[0]),
    .R(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_schedule.v:104.5-170.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _127_ (
    .C(clk),
    .CE(_022_),
    .D(_026_[1]),
    .Q(current_floor[1]),
    .R(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_schedule.v:104.5-170.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _128_ (
    .C(clk),
    .CE(_021_),
    .D(state_d[0]),
    .Q(state_q[0]),
    .R(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_schedule.v:104.5-170.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _129_ (
    .C(clk),
    .CE(_021_),
    .D(state_d[1]),
    .Q(state_q[1]),
    .R(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_schedule.v:104.5-170.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _130_ (
    .C(clk),
    .CE(_021_),
    .D(state_d[2]),
    .Q(state_q[2]),
    .R(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_schedule.v:104.5-170.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _131_ (
    .C(clk),
    .CE(_036_[0]),
    .D(_030_[0]),
    .Q(move_timer[0]),
    .R(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_schedule.v:104.5-170.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _132_ (
    .C(clk),
    .CE(1'h1),
    .D(_029_),
    .Q(move_timer[1]),
    .R(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_schedule.v:104.5-170.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _133_ (
    .C(clk),
    .CE(1'h1),
    .D(_028_),
    .Q(door_timer[0]),
    .R(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_schedule.v:104.5-170.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _134_ (
    .C(clk),
    .CE(1'h1),
    .D(_027_),
    .Q(door_timer[1]),
    .R(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT4 #(
    .INIT(16'hf200)
  ) _135_ (
    .I0(door_open),
    .I1(state_q[2]),
    .I2(_030_[0]),
    .I3(move_timer[1]),
    .O(_029_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT6 #(
    .INIT(64'hefff1000eeee0000)
  ) _136_ (
    .I0(motor_down),
    .I1(motor_up),
    .I2(_034_[3]),
    .I3(door_timer[0]),
    .I4(door_timer[1]),
    .I5(_039_[2]),
    .O(_027_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT6 #(
    .INIT(64'hefeeefee00001011)
  ) _137_ (
    .I0(motor_down),
    .I1(motor_up),
    .I2(_034_[3]),
    .I3(_039_[2]),
    .I4(_036_[0]),
    .I5(door_timer[0]),
    .O(_028_)
  );
  assign _001_[5:3] = { current_floor[0], current_floor[1], state_q[0] };
  assign _041_[1:0] = { _034_[3], _039_[2] };
  assign { _042_[5], _042_[0] } = { _035_[1], emergency_stop };
  assign { _038_[4], _038_[2:0] } = { _001_[2], _033_[2], _036_[0], _033_[0] };
  assign _031_[5] = _025_[7];
  assign { _018_[6:3], _018_[1:0] } = { current_floor[1], state_q[0], emergency_stop, current_floor[0], _001_[1], _001_[2] };
  assign _039_[1:0] = door_timer;
  assign _035_[0] = _034_[0];
  assign _034_[4] = state_q[0];
  assign { _043_[5:2], _043_[0] } = { _040_[1], _015_[0], _025_[0], _033_[2], _033_[0] };
  assign _036_[1] = door_timer[0];
  assign { _033_[4], _033_[1] } = { _015_[0], _025_[0] };
  assign { _040_[5:2], _040_[0] } = { _001_[6], current_floor[1], state_q[0], current_floor[0], _033_[5] };
  assign { _037_[5], _037_[3:0] } = { _035_[4], _034_[2], _035_[1], _034_[1:0] };
  assign { _023_[31:2], _023_[0] } = { 30'h3fffffff, next_floor_dn[0] };
  assign { _025_[30:25], _025_[3] } = _015_;
  assign _026_[0] = next_floor_dn[0];
  assign i = 32'd4;
  assign next_floor_up[0] = next_floor_dn[0];
  assign saved_dir = 1'h0;
  assign state_dbg = state_q;
endmodule

(* src = "clk_divider.v:3.1-29.10" *)
module clk_divider(clk_100mhz, rst, clk_1hz);
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:84.12-84.14" *)
  wire _00_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:84.16-84.18" *)
  wire _01_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _02_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:84.12-84.14" *)
  wire _03_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:84.16-84.18" *)
  wire _04_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/bin/../share/yosys/xilinx/lut_map.v:78.12-78.14" *)
  wire _05_;
  wire _06_;
  (* force_downto = 32'd1 *)
  (* src = "clk_divider.v:24.28-24.39|/usr/bin/../share/yosys/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 12 13 14 16 17 18 20 21 22 24 25" *)
  wire [25:0] _07_;
  (* force_downto = 32'd1 *)
  (* src = "clk_divider.v:24.28-24.39|/usr/bin/../share/yosys/xilinx/arith_map.v:112.23-112.24" *)
  wire [25:0] _08_;
  (* force_downto = 32'd1 *)
  (* src = "clk_divider.v:24.28-24.39|/usr/bin/../share/yosys/xilinx/arith_map.v:112.26-112.27" *)
  wire [25:0] _09_;
  (* force_downto = 32'd1 *)
  (* src = "clk_divider.v:24.28-24.39|/usr/bin/../share/yosys/xilinx/arith_map.v:170.23-170.24" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 12 13 14 16 17 18 20 21 22 24 25 26 27" *)
  wire [27:0] _10_;
  (* force_downto = 32'd1 *)
  (* src = "clk_divider.v:24.28-24.39|/usr/bin/../share/yosys/xilinx/arith_map.v:168.23-168.24" *)
  (* unused_bits = "26 27" *)
  wire [27:0] _11_;
  wire _12_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [4:0] _13_;
  (* src = "clk_divider.v:4.17-4.27" *)
  input clk_100mhz;
  wire clk_100mhz;
  (* src = "clk_divider.v:6.17-6.24" *)
  output clk_1hz;
  wire clk_1hz;
  (* src = "clk_divider.v:9.16-9.23" *)
  wire [25:0] counter;
  (* src = "clk_divider.v:5.17-5.20" *)
  input rst;
  wire rst;
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h8000)
  ) _14_ (
    .I0(counter[14]),
    .I1(counter[15]),
    .I2(counter[19]),
    .I3(counter[25]),
    .O(_13_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _15_ (
    .I0(1'h0),
    .I1(1'h0),
    .O(_00_),
    .S(counter[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h8000000000000000)
  ) _16_ (
    .I0(counter[1]),
    .I1(counter[2]),
    .I2(counter[3]),
    .I3(counter[4]),
    .I4(counter[5]),
    .I5(counter[6]),
    .O(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _17_ (
    .I0(1'h0),
    .I1(_02_),
    .O(_01_),
    .S(counter[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:87.13-87.52" *)
  MUXF8 _18_ (
    .I0(_00_),
    .I1(_01_),
    .O(_13_[0]),
    .S(counter[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h4000000000000000)
  ) _19_ (
    .I0(counter[7]),
    .I1(counter[22]),
    .I2(counter[20]),
    .I3(counter[17]),
    .I4(counter[21]),
    .I5(counter[23]),
    .O(_13_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _20_ (
    .I0(1'h0),
    .I1(1'h0),
    .O(_03_),
    .S(counter[24])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/bin/../share/yosys/xilinx/lut_map.v:79.45-79.70|/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h0000000000000001)
  ) _21_ (
    .I0(counter[8]),
    .I1(counter[9]),
    .I2(counter[10]),
    .I3(counter[11]),
    .I4(counter[16]),
    .I5(counter[18]),
    .O(_05_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _22_ (
    .I0(_05_),
    .I1(1'h0),
    .O(_04_),
    .S(counter[24])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:87.13-87.52" *)
  MUXF8 _23_ (
    .I0(_03_),
    .I1(_04_),
    .O(_13_[2]),
    .S(counter[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4294934528)
  ) _24_ (
    .I0(_13_[0]),
    .I1(_13_[1]),
    .I2(_13_[2]),
    .I3(_13_[3]),
    .I4(rst),
    .O(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _25_ (
    .I(counter[0]),
    .O(_08_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:24.28-24.39|/usr/bin/../share/yosys/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _26_ (
    .CI(1'h0),
    .CO(_07_[3:0]),
    .CYINIT(1'h0),
    .DI(4'h1),
    .O(_09_[3:0]),
    .S({ counter[3:1], _08_[0] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:24.28-24.39|/usr/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _27_ (
    .CI(_07_[3]),
    .CO(_07_[7:4]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_09_[7:4]),
    .S(counter[7:4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:24.28-24.39|/usr/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _28_ (
    .CI(_07_[7]),
    .CO(_07_[11:8]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_09_[11:8]),
    .S(counter[11:8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:24.28-24.39|/usr/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _29_ (
    .CI(_07_[11]),
    .CO(_07_[15:12]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_09_[15:12]),
    .S(counter[15:12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:24.28-24.39|/usr/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _30_ (
    .CI(_07_[15]),
    .CO(_07_[19:16]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_09_[19:16]),
    .S(counter[19:16])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:24.28-24.39|/usr/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _31_ (
    .CI(_07_[19]),
    .CO(_07_[23:20]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_09_[23:20]),
    .S(counter[23:20])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:24.28-24.39|/usr/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _32_ (
    .CI(_07_[23]),
    .CO({ _10_[27:26], _07_[25:24] }),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O({ _11_[27:26], _09_[25:24] }),
    .S({ 2'h0, counter[25:24] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _33_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_12_),
    .Q(clk_1hz),
    .R(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _34_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_09_[0]),
    .Q(counter[0]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _35_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_09_[1]),
    .Q(counter[1]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _36_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_09_[2]),
    .Q(counter[2]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _37_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_09_[3]),
    .Q(counter[3]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _38_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_09_[4]),
    .Q(counter[4]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _39_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_09_[5]),
    .Q(counter[5]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _40_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_09_[6]),
    .Q(counter[6]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _41_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_09_[7]),
    .Q(counter[7]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _42_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_09_[8]),
    .Q(counter[8]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _43_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_09_[9]),
    .Q(counter[9]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _44_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_09_[10]),
    .Q(counter[10]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _45_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_09_[11]),
    .Q(counter[11]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _46_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_09_[12]),
    .Q(counter[12]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _47_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_09_[13]),
    .Q(counter[13]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _48_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_09_[14]),
    .Q(counter[14]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _49_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_09_[15]),
    .Q(counter[15]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _50_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_09_[16]),
    .Q(counter[16]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _51_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_09_[17]),
    .Q(counter[17]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _52_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_09_[18]),
    .Q(counter[18]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _53_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_09_[19]),
    .Q(counter[19]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _54_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_09_[20]),
    .Q(counter[20]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _55_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_09_[21]),
    .Q(counter[21]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _56_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_09_[22]),
    .Q(counter[22]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _57_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_09_[23]),
    .Q(counter[23]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _58_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_09_[24]),
    .Q(counter[24]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "clk_divider.v:13.5-27.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _59_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(_09_[25]),
    .Q(counter[25]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  LUT5 #(
    .INIT(32'd2147450880)
  ) _60_ (
    .I0(_13_[2]),
    .I1(_13_[1]),
    .I2(_13_[0]),
    .I3(_13_[3]),
    .I4(clk_1hz),
    .O(_12_)
  );
  assign _13_[4] = rst;
  assign _08_[25:1] = counter[25:1];
  assign _10_[25:0] = _07_;
  assign _11_[25:0] = _09_;
endmodule

(* src = "debouncer.v:2.1-53.10" *)
module debouncer(clk_100mhz, rst, raw_in, db_out);
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:84.12-84.14" *)
  wire _00_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:84.16-84.18" *)
  wire _01_;
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* force_downto = 32'd1 *)
  (* src = "debouncer.v:48.31-48.45|/usr/bin/../share/yosys/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 12 13 14 16 17 18" *)
  wire [18:0] _06_;
  (* force_downto = 32'd1 *)
  (* src = "debouncer.v:48.31-48.45|/usr/bin/../share/yosys/xilinx/arith_map.v:112.23-112.24" *)
  wire [18:0] _07_;
  (* force_downto = 32'd1 *)
  (* src = "debouncer.v:48.31-48.45|/usr/bin/../share/yosys/xilinx/arith_map.v:112.26-112.27" *)
  wire [18:0] _08_;
  (* force_downto = 32'd1 *)
  (* src = "debouncer.v:48.31-48.45|/usr/bin/../share/yosys/xilinx/arith_map.v:170.23-170.24" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 12 13 14 16 17 18 19" *)
  wire [19:0] _09_;
  (* force_downto = 32'd1 *)
  (* src = "debouncer.v:48.31-48.45|/usr/bin/../share/yosys/xilinx/arith_map.v:168.23-168.24" *)
  (* unused_bits = "19" *)
  wire [19:0] _10_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _11_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [5:0] _12_;
  (* src = "debouncer.v:5.17-5.27" *)
  input clk_100mhz;
  wire clk_100mhz;
  (* src = "debouncer.v:8.17-8.23" *)
  output db_out;
  wire db_out;
  (* src = "debouncer.v:31.16-31.25" *)
  wire last_sync;
  (* src = "debouncer.v:7.17-7.23" *)
  input raw_in;
  wire raw_in;
  (* src = "debouncer.v:6.17-6.20" *)
  input rst;
  wire rst;
  (* src = "debouncer.v:30.16-30.26" *)
  wire [18:0] stable_cnt;
  (* src = "debouncer.v:14.9-14.17" *)
  wire sync_ff1;
  (* src = "debouncer.v:14.19-14.27" *)
  wire sync_ff2;
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd2147483647)
  ) _13_ (
    .I0(_12_[5]),
    .I1(_12_[1]),
    .I2(_12_[2]),
    .I3(_12_[3]),
    .I4(_12_[4]),
    .O(_05_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _14_ (
    .I0(1'h0),
    .I1(1'h0),
    .O(_00_),
    .S(stable_cnt[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h0100000000000000)
  ) _15_ (
    .I0(stable_cnt[5]),
    .I1(stable_cnt[6]),
    .I2(stable_cnt[7]),
    .I3(stable_cnt[16]),
    .I4(stable_cnt[18]),
    .I5(stable_cnt[2]),
    .O(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _16_ (
    .I0(1'h0),
    .I1(_02_),
    .O(_01_),
    .S(stable_cnt[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:87.13-87.52" *)
  MUXF8 _17_ (
    .I0(_00_),
    .I1(_01_),
    .O(_12_[5]),
    .S(stable_cnt[17])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h80)
  ) _18_ (
    .I0(stable_cnt[8]),
    .I1(stable_cnt[13]),
    .I2(stable_cnt[15]),
    .O(_12_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _19_ (
    .I0(stable_cnt[14]),
    .I1(stable_cnt[0]),
    .O(_12_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h8)
  ) _20_ (
    .I0(stable_cnt[1]),
    .I1(stable_cnt[3]),
    .O(_12_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h0001)
  ) _21_ (
    .I0(stable_cnt[9]),
    .I1(stable_cnt[10]),
    .I2(stable_cnt[11]),
    .I3(stable_cnt[12]),
    .O(_12_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _22_ (
    .I0(sync_ff2),
    .I1(last_sync),
    .O(_11_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'he)
  ) _23_ (
    .I0(_11_[0]),
    .I1(rst),
    .O(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h4000000000000000)
  ) _24_ (
    .I0(_11_[0]),
    .I1(_12_[1]),
    .I2(_12_[2]),
    .I3(_12_[3]),
    .I4(_12_[4]),
    .I5(_12_[5]),
    .O(_03_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _25_ (
    .I(stable_cnt[0]),
    .O(_07_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:48.31-48.45|/usr/bin/../share/yosys/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _26_ (
    .CI(1'h0),
    .CO(_06_[3:0]),
    .CYINIT(1'h0),
    .DI(4'h1),
    .O(_08_[3:0]),
    .S({ stable_cnt[3:1], _07_[0] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:48.31-48.45|/usr/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _27_ (
    .CI(_06_[3]),
    .CO(_06_[7:4]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_08_[7:4]),
    .S(stable_cnt[7:4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:48.31-48.45|/usr/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _28_ (
    .CI(_06_[7]),
    .CO(_06_[11:8]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_08_[11:8]),
    .S(stable_cnt[11:8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:48.31-48.45|/usr/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _29_ (
    .CI(_06_[11]),
    .CO(_06_[15:12]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_08_[15:12]),
    .S(stable_cnt[15:12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:48.31-48.45|/usr/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _30_ (
    .CI(_06_[15]),
    .CO({ _09_[19], _06_[18:16] }),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O({ _10_[19], _08_[18:16] }),
    .S({ 1'h0, stable_cnt[18:16] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:33.5-51.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _31_ (
    .C(clk_100mhz),
    .CE(_03_),
    .D(sync_ff2),
    .Q(db_out),
    .R(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:33.5-51.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _32_ (
    .C(clk_100mhz),
    .CE(_05_),
    .D(_08_[0]),
    .Q(stable_cnt[0]),
    .R(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:33.5-51.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _33_ (
    .C(clk_100mhz),
    .CE(_05_),
    .D(_08_[1]),
    .Q(stable_cnt[1]),
    .R(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:33.5-51.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _34_ (
    .C(clk_100mhz),
    .CE(_05_),
    .D(_08_[2]),
    .Q(stable_cnt[2]),
    .R(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:33.5-51.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _35_ (
    .C(clk_100mhz),
    .CE(_05_),
    .D(_08_[3]),
    .Q(stable_cnt[3]),
    .R(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:33.5-51.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _36_ (
    .C(clk_100mhz),
    .CE(_05_),
    .D(_08_[4]),
    .Q(stable_cnt[4]),
    .R(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:33.5-51.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _37_ (
    .C(clk_100mhz),
    .CE(_05_),
    .D(_08_[5]),
    .Q(stable_cnt[5]),
    .R(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:33.5-51.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _38_ (
    .C(clk_100mhz),
    .CE(_05_),
    .D(_08_[6]),
    .Q(stable_cnt[6]),
    .R(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:33.5-51.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _39_ (
    .C(clk_100mhz),
    .CE(_05_),
    .D(_08_[7]),
    .Q(stable_cnt[7]),
    .R(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:33.5-51.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _40_ (
    .C(clk_100mhz),
    .CE(_05_),
    .D(_08_[8]),
    .Q(stable_cnt[8]),
    .R(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:33.5-51.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _41_ (
    .C(clk_100mhz),
    .CE(_05_),
    .D(_08_[9]),
    .Q(stable_cnt[9]),
    .R(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:33.5-51.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _42_ (
    .C(clk_100mhz),
    .CE(_05_),
    .D(_08_[10]),
    .Q(stable_cnt[10]),
    .R(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:33.5-51.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _43_ (
    .C(clk_100mhz),
    .CE(_05_),
    .D(_08_[11]),
    .Q(stable_cnt[11]),
    .R(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:33.5-51.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _44_ (
    .C(clk_100mhz),
    .CE(_05_),
    .D(_08_[12]),
    .Q(stable_cnt[12]),
    .R(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:33.5-51.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _45_ (
    .C(clk_100mhz),
    .CE(_05_),
    .D(_08_[13]),
    .Q(stable_cnt[13]),
    .R(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:33.5-51.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _46_ (
    .C(clk_100mhz),
    .CE(_05_),
    .D(_08_[14]),
    .Q(stable_cnt[14]),
    .R(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:33.5-51.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _47_ (
    .C(clk_100mhz),
    .CE(_05_),
    .D(_08_[15]),
    .Q(stable_cnt[15]),
    .R(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:33.5-51.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _48_ (
    .C(clk_100mhz),
    .CE(_05_),
    .D(_08_[16]),
    .Q(stable_cnt[16]),
    .R(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:33.5-51.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _49_ (
    .C(clk_100mhz),
    .CE(_05_),
    .D(_08_[17]),
    .Q(stable_cnt[17]),
    .R(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:33.5-51.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _50_ (
    .C(clk_100mhz),
    .CE(_05_),
    .D(_08_[18]),
    .Q(stable_cnt[18]),
    .R(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:33.5-51.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _51_ (
    .C(clk_100mhz),
    .CE(_11_[0]),
    .D(sync_ff2),
    .Q(last_sync),
    .R(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:16.5-24.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _52_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(raw_in),
    .Q(sync_ff1),
    .R(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "debouncer.v:16.5-24.8|/usr/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _53_ (
    .C(clk_100mhz),
    .CE(1'h1),
    .D(sync_ff1),
    .Q(sync_ff2),
    .R(rst)
  );
  assign _12_[0] = _11_[0];
  assign _11_[1] = rst;
  assign _07_[18:1] = stable_cnt[18:1];
  assign _09_[18:0] = _06_;
  assign _10_[18:0] = _08_;
endmodule

(* top =  1  *)
(* src = "lift_top.v:2.1-99.10" *)
module lift_top(clk, rst, emergency_stop, floor_request, door_obstruction, door_open, motor_up, motor_down, state_dbg, digit, Seven_Seg);
  wire _00_;
  wire _01_;
  wire [7:0] _02_;
  wire _03_;
  wire [3:0] _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire [3:0] _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire [2:0] _12_;
  (* src = "lift_top.v:14.24-14.33" *)
  output [7:0] Seven_Seg;
  wire [7:0] Seven_Seg;
  (* src = "lift_top.v:3.24-3.27" *)
  input clk;
  wire clk;
  (* src = "lift_top.v:17.10-17.17" *)
  wire clk_1hz;
  (* src = "lift_top.v:22.16-22.29" *)
  wire [1:0] current_floor;
  (* src = "lift_top.v:13.24-13.29" *)
  output [3:0] digit;
  wire [3:0] digit;
  (* src = "lift_top.v:21.10-21.16" *)
  wire dob_db;
  (* src = "lift_top.v:7.24-7.40" *)
  input door_obstruction;
  wire door_obstruction;
  (* src = "lift_top.v:8.24-8.33" *)
  output door_open;
  wire door_open;
  (* src = "lift_top.v:5.24-5.38" *)
  input emergency_stop;
  wire emergency_stop;
  (* src = "lift_top.v:19.10-19.16" *)
  wire emg_db;
  (* src = "lift_top.v:6.24-6.37" *)
  input [3:0] floor_request;
  wire [3:0] floor_request;
  (* src = "lift_top.v:20.16-20.21" *)
  wire [3:0] fr_db;
  (* src = "lift_top.v:10.24-10.34" *)
  output motor_down;
  wire motor_down;
  (* src = "lift_top.v:9.24-9.32" *)
  output motor_up;
  wire motor_up;
  (* src = "lift_top.v:4.24-4.27" *)
  input rst;
  wire rst;
  (* src = "lift_top.v:18.10-18.16" *)
  wire rst_db;
  (* src = "lift_top.v:11.24-11.33" *)
  output [2:0] state_dbg;
  wire [2:0] state_dbg;
  BUFG _13_ (
    .I(_00_),
    .O(_03_)
  );
  BUFG _14_ (
    .I(_01_),
    .O(clk_1hz)
  );
  (* keep = 32'd1 *)
  OBUF _15_ (
    .I(_02_[0]),
    .O(Seven_Seg[0])
  );
  (* keep = 32'd1 *)
  OBUF _16_ (
    .I(_02_[1]),
    .O(Seven_Seg[1])
  );
  (* keep = 32'd1 *)
  OBUF _17_ (
    .I(_02_[2]),
    .O(Seven_Seg[2])
  );
  (* keep = 32'd1 *)
  OBUF _18_ (
    .I(_02_[3]),
    .O(Seven_Seg[3])
  );
  (* keep = 32'd1 *)
  OBUF _19_ (
    .I(_02_[4]),
    .O(Seven_Seg[4])
  );
  (* keep = 32'd1 *)
  OBUF _20_ (
    .I(_02_[5]),
    .O(Seven_Seg[5])
  );
  (* keep = 32'd1 *)
  OBUF _21_ (
    .I(_02_[6]),
    .O(Seven_Seg[6])
  );
  (* keep = 32'd1 *)
  OBUF _22_ (
    .I(_02_[7]),
    .O(Seven_Seg[7])
  );
  (* keep = 32'd1 *)
  IBUF _23_ (
    .I(clk),
    .O(_00_)
  );
  (* keep = 32'd1 *)
  OBUF _24_ (
    .I(_04_[0]),
    .O(digit[0])
  );
  (* keep = 32'd1 *)
  OBUF _25_ (
    .I(_04_[1]),
    .O(digit[1])
  );
  (* keep = 32'd1 *)
  OBUF _26_ (
    .I(_04_[2]),
    .O(digit[2])
  );
  (* keep = 32'd1 *)
  OBUF _27_ (
    .I(_04_[3]),
    .O(digit[3])
  );
  (* keep = 32'd1 *)
  IBUF _28_ (
    .I(door_obstruction),
    .O(_05_)
  );
  (* keep = 32'd1 *)
  OBUF _29_ (
    .I(_06_),
    .O(door_open)
  );
  (* keep = 32'd1 *)
  IBUF _30_ (
    .I(emergency_stop),
    .O(_07_)
  );
  (* keep = 32'd1 *)
  IBUF _31_ (
    .I(floor_request[0]),
    .O(_08_[0])
  );
  (* keep = 32'd1 *)
  IBUF _32_ (
    .I(floor_request[1]),
    .O(_08_[1])
  );
  (* keep = 32'd1 *)
  IBUF _33_ (
    .I(floor_request[2]),
    .O(_08_[2])
  );
  (* keep = 32'd1 *)
  IBUF _34_ (
    .I(floor_request[3]),
    .O(_08_[3])
  );
  (* keep = 32'd1 *)
  OBUF _35_ (
    .I(_09_),
    .O(motor_down)
  );
  (* keep = 32'd1 *)
  OBUF _36_ (
    .I(_10_),
    .O(motor_up)
  );
  (* keep = 32'd1 *)
  IBUF _37_ (
    .I(rst),
    .O(_11_)
  );
  (* keep = 32'd1 *)
  OBUF _38_ (
    .I(_12_[0]),
    .O(state_dbg[0])
  );
  (* keep = 32'd1 *)
  OBUF _39_ (
    .I(_12_[1]),
    .O(state_dbg[1])
  );
  (* keep = 32'd1 *)
  OBUF _40_ (
    .I(_12_[2]),
    .O(state_dbg[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_top.v:54.23-59.14" *)
  debouncer \gen_fr_db[0].u_db_fr  (
    .clk_100mhz(_03_),
    .db_out(fr_db[0]),
    .raw_in(_08_[0]),
    .rst(rst_db)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_top.v:54.23-59.14" *)
  debouncer \gen_fr_db[1].u_db_fr  (
    .clk_100mhz(_03_),
    .db_out(fr_db[1]),
    .raw_in(_08_[1]),
    .rst(rst_db)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_top.v:54.23-59.14" *)
  debouncer \gen_fr_db[2].u_db_fr  (
    .clk_100mhz(_03_),
    .db_out(fr_db[2]),
    .raw_in(_08_[2]),
    .rst(rst_db)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_top.v:54.23-59.14" *)
  debouncer \gen_fr_db[3].u_db_fr  (
    .clk_100mhz(_03_),
    .db_out(fr_db[3]),
    .raw_in(_08_[3]),
    .rst(rst_db)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_top.v:27.17-31.6" *)
  clk_divider u_clk_div (
    .clk_100mhz(_03_),
    .clk_1hz(_01_),
    .rst(_11_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_top.v:63.15-68.6" *)
  debouncer u_db_dob (
    .clk_100mhz(_03_),
    .db_out(dob_db),
    .raw_in(_05_),
    .rst(rst_db)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_top.v:44.15-49.6" *)
  debouncer u_db_emg (
    .clk_100mhz(_03_),
    .db_out(emg_db),
    .raw_in(_07_),
    .rst(rst_db)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_top.v:37.15-42.6" *)
  debouncer u_db_rst (
    .clk_100mhz(_03_),
    .db_out(rst_db),
    .raw_in(_11_),
    .rst(1'h0)
  );
  (* src = "lift_top.v:77.7-88.6" *)
  \$paramod$73e12f780b28ea4983629c398f0c11da23bd7b50\lift_schedule  u_lift (
    .clk(clk_1hz),
    .current_floor(current_floor),
    .door_obstruction(dob_db),
    .door_open(_06_),
    .emergency_stop(emg_db),
    .floor_request(fr_db),
    .motor_down(_09_),
    .motor_up(_10_),
    .rst(rst_db),
    .state_dbg(_12_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lift_top.v:93.18-97.6" *)
  seg7_display u_seg7 (
    .Seven_Seg(_02_),
    .current_floor(current_floor),
    .digit(_04_)
  );
endmodule

(* src = "seg7_display.v:27.1-52.10" *)
module seg7_display(current_floor, digit, Seven_Seg);
  (* src = "seg7_display.v:30.23-30.32" *)
  output [7:0] Seven_Seg;
  wire [7:0] Seven_Seg;
  (* src = "seg7_display.v:28.23-28.36" *)
  input [1:0] current_floor;
  wire [1:0] current_floor;
  (* src = "seg7_display.v:29.23-29.28" *)
  output [3:0] digit;
  wire [3:0] digit;
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _0_ (
    .I0(current_floor[0]),
    .I1(current_floor[1]),
    .O(Seven_Seg[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _1_ (
    .I0(current_floor[1]),
    .I1(current_floor[0]),
    .O(Seven_Seg[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'he)
  ) _2_ (
    .I0(current_floor[0]),
    .I1(current_floor[1]),
    .O(Seven_Seg[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _3_ (
    .I(current_floor[1]),
    .O(Seven_Seg[6])
  );
  assign { Seven_Seg[7], Seven_Seg[4], Seven_Seg[1:0] } = { 1'h1, current_floor[0], 1'h0, Seven_Seg[3] };
  assign digit = 4'h1;
endmodule
